### ISSUE TITLE
ci: Cross-arch test are failing

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-repo-config-python#145]
### What happened?

Cross arch test are failing because `python3 -m venv .venv` is failing.

### What did you expect instead?

The command to run correctly and tests to pass.

### Affected part(s)

Cookiecutter template (part:cookiecutter)

### Extra information

Sadly there is no output, just return code 1.

```
>       _run(repo_path, "python3", "-m", "venv", ".venv")

tests/integration/test_cookiecutter_generation.py:74: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/integration/test_cookiecutter_generation.py:126: in _run
    return subprocess.run(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = (('python3', '-m', 'venv', '.venv'),)
kwargs = {'cwd': PosixPath('/tmp/pytest-of-root/pytest-0/test_generation_RepositoryType0/frequenz-actor-test'), 'env': None}
process = <Popen: returncode: 1 args: ('python3', '-m', 'venv', '.venv')>
stdout = None, stderr = None, retcode = 1
```

### TODO

- [x] #151 
- [x] #152
- [x] Add the `cross-arch-all` job to the branch protection rules when this is fixed

**Comment by llucax** [comment]
@tiyash-basu-frequenz maybe you can provide some help, since the CI is using github actions to setup que qemu environment, if you have any easy guides on how to do the same in Debian/Ubuntu, it would be of great help, so I can test this locally.

**Comment by tiyash-basu-frequenz** [comment]
Before I jump into QEMU stuff, does this work with `python` instead of `python3`?

If you look at the lines [here](https://github.com/frequenz-floss/frequenz-repo-config-python/blob/330bb2d5803e4ef96e8108e72d5d763137a6a913/.github/containers/nox-cross-arch/arm64-ubuntu-20.04-python-3.11.Dockerfile#L28-L30) in the image, there is no `python3` binary in the image.
```
RUN update-alternatives --install \
        /usr/local/bin/python python /usr/bin/python3.11 1 && \
    python -m pip install --upgrade --no-cache-dir pip
```

**Comment by llucax** [comment]
This is working on the SDK, and you are updating the *alternatives* to make `python` an alias to `python3.11`, so I doubt it is an issue with the python version. As a sidenote we can also skip the `update-alternatives` and use `python3.11` explicitly instead to avoid messing with the base system.

**Comment by tiyash-basu-frequenz** [comment]
> This is working on the SDK, and you are updating the alternatives to make python an alias to python3.11, so I doubt it is an issue with the python version. 

What I was trying to say is that a `python3` file could simply be missing in the image. But if you say it works in the SDK, then okay.

>As a sidenote we can also skip the update-alternatives and use python3.11 explicitly instead to avoid messing with the base system.

For me, it would be quite awkward to have an image specifically built (and tagged) for a specific python version, and then having to use `python<version>`. We should be able to use just `python` and `pip` (or `python3` and `pip3`), otherwise tooling with multiple images with different python versions will become very difficult.

**Comment by tiyash-basu-frequenz** [comment]
>  if you have any easy guides on how to do the same in Debian/Ubuntu, it would be of great help, so I can test this locally.

I do not have something handy, but a quick web search led me here: https://futurewei-cloud.github.io/ARM-Datacenter/qemu/how-to-launch-aarch64-vm/

Maybe you could also use libvirt: https://www.thegeekstuff.com/2014/10/linux-kvm-create-guest-vm/

**Comment by tiyash-basu-frequenz** [comment]
I checked, and can confirm that `which python3` returns `/usr/bin/python3` for tthe cross-arch test image in the SDK. So we can definitely close that avenue of investigation.

**Comment by tiyash-basu-frequenz** [comment]
~@llucax can you please post a link to the failed CI run?~

nvm, I ran it in CI in my fork, and have the logs.

**Comment by tiyash-basu-frequenz** [comment]
We need to extend the docker image. Here is the error I got by just running `python3 -m venv .venv` in the CI step:
```
> Run docker run \
  docker run \
    --rm \
    -v $(pwd)://home/runner/work/frequenz-repo-config-python/frequenz-repo-config-python \
    -v /tmp/pip-cache:/root/.cache/pip \
    -w /home/runner/work/frequenz-repo-config-python/frequenz-repo-config-python \
    --net=host \
    --platform linux/arm64 \
    localhost/nox-cross-arch:latest \
    bash -c "python3 -m venv .venv"
  shell: /usr/bin/bash -e {0}
  env:
    DEFAULT_PYTHON_VERSION: 3.11
System details: Linux fv-az[2](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328155816/job/17185661004#step:10:2)00-181 5.15.0-1046-azure #5[3](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328155816/job/17185661004#step:10:3)~20.0[4](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328155816/job/17185661004#step:10:4).1-Ubuntu SMP Mon Aug 28 14:17:23 UTC 2023 aarch[6](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328155816/job/17185661004#step:10:6)4 aarch64 aarch64 GNU/Linux
Machine: aarch64
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.[8](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328155816/job/17185661004#step:10:8)-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/runner/work/frequenz-repo-config-python/frequenz-repo-config-python/.venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```
https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328155816/job/17185661004

The reason it says `python3.8-venv` is very likely because the image has python 3.8 (I think as git's dependency), and `python3` defaults to python 3.8. So we should set up a sym link for python3 as well, and point it to python 3.11.

I am [testing](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328524836) it anyway, so will make a PR at the end of the process.

**Comment by tiyash-basu-frequenz** [comment]
Looks like the `python3 -m venv .venv` command is not an issue anymore. [Here](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328950652/job/17188228907) is a test where it runs. This is an updated branch where I run this command instead of the tests.

However, the [entire tests](https://github.com/tiyash-basu-frequenz/frequenz-repo-config-python/actions/runs/6328524836/job/17186883769) took more than 30 minutes in a test run, and timed out.

**Comment by llucax** [comment]
Great findings, thanks for having a look.

I wonder why this works on the SDK, though, as pip is also used there 🤔. It doesn create a venv, right? So maybe the issue is pip inside the venv?

**Comment by tiyash-basu-frequenz** [comment]
>It doesn create a venv, right? So maybe the issue is pip inside the venv?

Pretty sure. Otherwise we'd see the same issue there too.

**Comment by llucax** [comment]
> However, the entire tests took more than 30 minutes in a test run, and timed out.

Yeah, these tests are very slow, maybe besides these issues we should really not run the tests for the template generation in other archs. Eventually we need to increase the test coverage in the lib tests themselves anyway...

**Comment by llucax** [comment]
So you have a version that is working but just have tests timing out because they take too long, right?

**Comment by tiyash-basu-frequenz** [comment]
> So you have a version that is working but just have tests timing out because they take too long, right?

Yeah. I just made a PR here: https://github.com/frequenz-floss/frequenz-repo-config-python/pull/151

(Please feel free to close it if you think this should be handled in a different way, or at a different level)

**Comment by llucax** [comment]
Great thanks!
